import * as Cache from "./cache";
import * as Config from "./config";
import * as Locale from "./locale";
import * as Comparer from "./comparer";
import * as Package from "./package";
export const cache = Cache;
export const config = Config;
export const locale = Locale;
export const comparer = Comparer;
export const packageJson = Package;
